name: Push

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: cypress-mock-openapi
        uses: cypress-io/github-action@v2
        with:
          command: yarn test
          working-directory: packages/cypress-mock-openapi

      - name: Upload test artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
